"""init_db

Revision ID: ebc31476d08d
Revises: 
Create Date: 2026-03-11 21:45:53.754763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc31476d08d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('transaction_type', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('sign', sa.Text(), nullable=False),
    sa.Column('signer_cert', sa.Text(), nullable=False),
    sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('transaction_in', sa.String(length=64), nullable=True),
    sa.Column('transaction_out', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_transactions_hash'), 'transactions', ['hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_hash'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
